
    create table biciclette (
        id integer not null,
        id_freno integer,
        id_sospensione integer,
        numero_marce integer not null,
        pieghevole boolean not null,
        primary key (id)
    );

    create table categorie (
        id integer generated by default as identity,
        categoria varchar(100) not null,
        primary key (id)
    );

    create table colori (
        id integer generated by default as identity,
        colore varchar(100) not null,
        primary key (id)
    );

    create table macchine (
        cc integer not null,
        id integer not null,
        numero_porte integer not null,
        targa varchar(255) not null unique,
        primary key (id)
    );

    create table marche (
        id integer generated by default as identity,
        marca varchar(100) not null,
        primary key (id)
    );

    create table moto (
        cc integer not null,
        id integer not null,
        numero_marce integer not null,
        targa varchar(255) not null unique,
        primary key (id)
    );

    create table tipi_alimentazione (
        id integer generated by default as identity,
        tipo_alimentazione varchar(100) not null,
        primary key (id)
    );

    create table tipi_freno (
        id integer generated by default as identity,
        tipo_freno varchar(100) not null,
        primary key (id)
    );

    create table tipi_sospensione (
        id integer generated by default as identity,
        tipo_sospensione varchar(100) not null,
        primary key (id)
    );

    create table tipi_veicolo (
        id integer generated by default as identity,
        tipo_veicolo varchar(100) not null,
        primary key (id)
    );

    create table veicoli (
        anno_produzione integer not null,
        id integer generated by default as identity,
        id_alimentazione integer,
        id_categoria integer,
        id_colore integer,
        id_marca integer,
        id_tipo integer,
        numero_ruote integer not null,
        primary key (id)
    );

    alter table if exists biciclette 
       add constraint FKi4e2ii6pf8yicufxmjtxr0uhw 
       foreign key (id_freno) 
       references tipi_freno;

    alter table if exists biciclette 
       add constraint FKql7mhtcmt9sv5ve9d1yp19fx0 
       foreign key (id_sospensione) 
       references tipi_sospensione;

    alter table if exists biciclette 
       add constraint FKrjqihljxxpydep024s0tusq2l 
       foreign key (id) 
       references veicoli;

    alter table if exists macchine 
       add constraint FKqttmt8yqk5vj8g3tn94ovrbay 
       foreign key (id) 
       references veicoli;

    alter table if exists moto 
       add constraint FKt01inn1jct6p6irfuar0pt15d 
       foreign key (id) 
       references veicoli;

    alter table if exists veicoli 
       add constraint FKfnj6d8ledmyr1pj05o2aunbga 
       foreign key (id_categoria) 
       references categorie;

    alter table if exists veicoli 
       add constraint FK9fby65ukehcfx0sd0pmaewyry 
       foreign key (id_colore) 
       references colori;

    alter table if exists veicoli 
       add constraint FKiv5idk7drutlxyxhc5663nwey 
       foreign key (id_marca) 
       references marche;

    alter table if exists veicoli 
       add constraint FK4up3dthh5qgmlf9twr26yo9tm 
       foreign key (id_alimentazione) 
       references tipi_alimentazione;

    alter table if exists veicoli 
       add constraint FK1hg9ov4pnip3yxdm5ew3bbi57 
       foreign key (id_tipo) 
       references tipi_veicolo;
